### ISSUE TITLE
Unicode strings issue

### ISSUE THREAD

**Issue by Kvaz1r** [texus/TGUI#105]
I want use unicode string in my application, but get strange result. If I use wide-string literal is correct display but incorrect write to file(could be reproducing with gui-builder). If I use usual string literal the behaviour is totally reversed(display incorrect, write correct).  

MCVE:

```
#include <TGUI/TGUI.hpp>

int main()
{
	sf::RenderWindow window(sf::VideoMode(800, 600), "TGUI window");
	tgui::Gui gui(window);
	tgui::MenuBar::Ptr menuBar = tgui::MenuBar::create();
	menuBar->addMenu(L"Текст");
	menuBar->addMenu("Текст2");
	gui.add(menuBar);
	gui.saveWidgetsToFile("test.txt");
	while (window.isOpen())
	{
		sf::Event event;
		while (window.pollEvent(event))
		{
			if (event.type == sf::Event::Closed)
				window.close();

			gui.handleEvent(event); // Pass the event to the widgets
		}

		window.clear();
		gui.draw(); // Draw all widgets
		window.display();
	}
}
```

**Comment by texus** [comment]
Saving and loading wasn't tested with unicode characters and it indeed doesn't work. On linux, neither of these strings are even written correctly.

I actually wrote a String class myself that I was going to use for TGUI 0.9 which would probably have solved this issue automatically (as it would always convert to UTF8 when needing an std::string), but I can't use that yet for backward compatibility.

I'll try to fix this soon by always outputting a UTF8 file when writing and assuming an UTF8 file encoding when reading.

The second addMenu call is never going to work, if my code is fixed then it will both display incorrectly and write incorrectly. So the first addMenu call is the correct way to use unicode characters.

**Comment by texus** [comment]
I've implemented a potential fix. It works on linux but you will have to test for yourself if the issue is also fixed on windows.

The code isn't 100% backwards compatible, but probably nobody is going to notice (unless they use the internal DataIO class or have a custom widget that can be saved and loaded from/to a text file).

**Comment by Kvaz1r** [comment]
Unfortunately nothing changed.

**Comment by texus** [comment]
I should have known if I thought about it longer. The reading/writing is probably still dependent on the locale, it just works on linux because it uses UTF8 as locale. I'll try to fix that tomorrow.

**Comment by texus** [comment]
When I started debugging this morning it didn't seem to work either, but it suddenly started working at some point. After a complete rebuild I can only conclude that it should work on windows as well.

There are some things you can try checking (the second one is what I believe might be the problem):
- Try writing to a new file and not an existing file (just in case it would be possible for a BOM to be cached).
- Maybe your cpp file encoding isn't correct? I recommend against putting unicode characters in your source files. Try using `menuBar->addMenu(L"\u0422\u0435\u043A\u0441\u0442");` instead.
- Make sure you are definately using the libraries from the version where I added the fix and aren't still linking to an older version.

**Comment by Kvaz1r** [comment]
No, I will try to found reason on this week(maybe it's some mess while I had rebuild the library or something) and for now try avoid all non-ASCII symbols. 
But it's definitely not encoding cause I set it via Geany separately to utf8 just to make sure. 
In wxWidgets there is wxString::FromUTF8 function just for such cases but I don't found analogue in SFML.

**Comment by Kvaz1r** [comment]
I totally rebuild the library and the issue fixed now.
