### ISSUE TITLE
Leaking MouseButtonPressed events through the MenuBar menus

### ISSUE THREAD

**Issue by x-qq** [texus/TGUI#120]
I have encountered a problem that makes it basically impossible to use TGUI for me.

SFML emits two events for every mouse click: first MouseButtonPressed, then MouseButtonReleased.

When clicking on TGUI MenuBar menu, the first event (MouseButtonPressed) does not get marked as handled, in other words tgui.handleEvent(); does not return true for it, and only returns true for the second event (MouseButtonReleased). This results in MouseButtonReleased events created by clicking on MenuBar menus "leaking" through it onto the underlying (currently invisible) UI elements, causing unintended clicks on things.

Example application - handleEvent() result with MouseButtonPressed events is always false:
```
#include <TGUI/TGUI.hpp>
#include <iostream>

int main()
{
    sf::RenderWindow window(sf::VideoMode(800, 600), "TGUI window");
    window.setFramerateLimit(60);

    int counter = 0;

    tgui::Gui gui(window);

    auto hello = [&] () {
        std::cout << "menubar callback happened at counter "
                  << counter << std::endl;
    };

    auto menu = tgui::MenuBar::create();

    menu->addMenuItem({"File", "Recent", "foo.pdf"});
    menu->connectMenuItem({"File", "Recent", "foo.pdf"}, hello);

    gui.add(menu);

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();

            bool washandled = gui.handleEvent(event);

            if (event.type == sf::Event::MouseButtonPressed) {
                std::cout << "did menu handle MouseButtonPressed? "
                          << std::boolalpha << washandled << std::endl;
                std::cout << "main loop got event at counter "
                          << counter << std::endl;
            }

            ++counter;
        }

        window.clear();
        gui.draw();
        window.display();


    }

    return EXIT_SUCCESS;
}
```
Output:
```
did menu handle MouseButtonPressed? false
main loop got event at counter 386
did menu handle MouseButtonPressed? false
main loop got event at counter 513
menubar callback happened at counter 514
```

Using TGUI 0.8.6

**Comment by texus** [comment]
I noticed this earlier when porting this to C#, this has already been fixed in https://github.com/texus/TGUI/commit/31940dfac52424f08dd6a0151a05204653d83ffd (after the release of 0.8.6)
