### ISSUE TITLE
Feature request: menubar separators

### ISSUE THREAD

**Issue by x-qq** [texus/TGUI#124]
I would like to replace native winapi menus in a program with a TGUI based menu, but some fairly important features seem to be missing. One of them is separators:

![scen](https://user-images.githubusercontent.com/55463047/73184599-64441400-4125-11ea-8475-2520db66b023.png)

Can this be added? Or is there perhaps a way to add separators with existing API?

Thanks.

**Comment by texus** [comment]
It isn't currently possible. I've added it to the todo list, but I don't have time these days to add non-trivial features. So unless you or someone else implements this, then this issue might stay open for a while.

**Comment by CelticMinstrel** [comment]
What I've typically seen (in WinAPI, Mac OS Toolkit pre-Carbon, and probably also Cocoa) is that menuitems named `"-"` (or perhaps just beginning with a `'-'`) automatically become a separator. That's not to say that this is necessarily the best or preferred API, but if it helps…

**Comment by texus** [comment]
Menu items with string "-" will now be replaced by separators.

4 new properties have been added to the renderer:
- SeparatorColor: color of the line
- SeparatorThickness: height of the line
- SeparatorVerticalPadding: additional space above and below the line
- SeparatorSidePadding: distance between the line and the side of the menu
