### ISSUE TITLE
how to connect a signal to a class function

### ISSUE THREAD

**Issue by iBinaryRocket** [texus/TGUI#133]
I have this function inside the SyHE space name and the class is called Windows, the problem is when trying to connect a button to a function inside the class, which compiles, but does nothing

namespace SyHE
{
    class SyHE
   {
        void show()
       {
            tgui::Button::ptr miBtnOk = tgui::Button::create(); 
            miBtnOk->connect("Unfocused", signalMensajeOpcion, this, miLabelOpcion, miBtnOk, 0);
       }

       void signalMensajeOpcion(tgui::Lable::Ptr mensaje, tgui::Button::Ptr btn, int e)
      {
            std::cout << "click" << std::endl;
       }
   }
}

**Comment by Kvaz1r** [comment]
I'm not sure that your code does compile, Clicked signal can only takes [optional parameter](https://tgui.eu/documentation/0.8/classtgui_1_1ClickableWidget.html#a4faa0a32ca37a34b509b79a350ac1aa5) "mouse position relative to widget.", Unfocused signal - doesn't accept any parameter. 
In any case if you want to use class member as callback just use proper syntax. Example:

```
#include <TGUI/TGUI.hpp>
#include <iostream>

class MyFrame
{
public:
    MyFrame()
    {
        window.create(sf::VideoMode(800, 600), "MCVE");
        gui.setTarget(window);

        auto miBtnOk = tgui::Button::create("Some button");
        miBtnOk->connect("Clicked", &MyFrame::signalMensajeOpcion, this);
        gui.add(miBtnOk);
    }

    void signalMensajeOpcion()
    {
        std::cout << "click" << std::endl;
    }

    void main()
    {
        while (window.isOpen())
        {
            sf::Event event;
            while (window.pollEvent(event))
            {
                if (event.type == sf::Event::Closed)
                    window.close();
                gui.handleEvent(event);
            }
            window.clear(sf::Color(232,232,232));
            gui.draw();
            window.display();
        }
    }
    sf::RenderWindow window;
    tgui::Gui gui;
};

int main()
{
    MyFrame().main();
}
```

If you really want to use some variables inside callback - use lambda or made them class members.

**Comment by iBinaryRocket** [comment]
Why does it work for you?

Look...
compiles but does nothing
![1](https://user-images.githubusercontent.com/67621621/86090975-b987a700-ba70-11ea-9107-1702c182497c.png)
![2](https://user-images.githubusercontent.com/67621621/86090983-bc829780-ba70-11ea-8056-4e5c8d0a0385.png)
![3](https://user-images.githubusercontent.com/67621621/86090995-bf7d8800-ba70-11ea-9050-88c0c102dc31.png)

**Comment by iBinaryRocket** [comment]
it should show a message on the left side

**Comment by iBinaryRocket** [comment]
sorry for the bad translation ... I speak Spanish and I use google translator

**Comment by Kvaz1r** [comment]
Your function have some arguments:
`tgui::Lable::Ptr mensaje, tgui::Button::Ptr btn, int e`

but accorging to the documentation for the callback shouldn't have any (for "Unfocused" or one optional Vector2f for "Clicked").

**Comment by iBinaryRocket** [comment]
no, it does not work...
![1](https://user-images.githubusercontent.com/67621621/86092444-1c7a3d80-ba73-11ea-93f1-f6eb6382b7b2.png)
![2](https://user-images.githubusercontent.com/67621621/86092448-1edc9780-ba73-11ea-9f90-e3f702220f24.png)
![3](https://user-images.githubusercontent.com/67621621/86092454-21d78800-ba73-11ea-8a16-9a27621c93d4.png)
![4](https://user-images.githubusercontent.com/67621621/86092459-2308b500-ba73-11ea-93b4-52830f37bd13.png)

**Comment by iBinaryRocket** [comment]
Can I send my code? ... maybe you see something that I don't

**Comment by Kvaz1r** [comment]
Yes, but if you describe what you expect to get it would be easier. I don't see part of code that show any messages except send string to std::cout.

**Comment by iBinaryRocket** [comment]
the idea is to get the signal, at the beginning it was to get a pointer to a label and change it, but it doesn't work and in order to better identify it, I decided to just put cout, but if you want to see my code and help me I would really appreciate it, just tell me where to send it

**Comment by Kvaz1r** [comment]
Github allow attach files, several source code files is totally acceptable or you can use service like https://dropmefiles.com

**Comment by iBinaryRocket** [comment]
Perfecto... look 
https://dropmefiles.com/aTfoV

**Comment by Kvaz1r** [comment]
You can't click on disable widget, remove this line:
` miBtnOk->setEnabled(false);`

Edit:

Clarifying to my comment above - user can't do any action with disabled widget.

**Comment by texus** [comment]
As Kvaz1r said, the problem is with calling setEnabled(false). Widgets will ignore events when they are disabled.

Your cout should also end with "\n" or you should use cerr instead of cout. Even after fixing setEnabled, the current code might not print anything in the command line until the program ends.

@Kvaz1r Passing parameters to the callback function is possible like that. There is no need to use a lambda or member variables if you need parameters in the function, the connect function can pass them for you. The Vector2f for Clicked is about unbound parameters (a parameter in the function that isn't provided when calling the connect function).
If there is something wrong with the parameters then you would either get a compile error (if bound parameter types don't match), an exception when calling the connect function (if unbound parameter type doesn't match with the signal).

**Comment by iBinaryRocket** [comment]
Jaja... ¡funcionó!...
the problem was not setEnabled (), although that led me to the problem; which was that I was linking the signal to another button and not the one I wanted ... Thanks for the support!

![1](https://user-images.githubusercontent.com/67621621/86201929-7c7dec00-bb26-11ea-98c3-bfbd79558970.png)
![2](https://user-images.githubusercontent.com/67621621/86201934-7ee04600-bb26-11ea-8490-86d9d9b94aa6.png)

**Comment by colesnicov** [comment]
Hello. I have a class:

```
namespace packet
class ModuleDesktop {
  public:
  void bindSignal(){
    button.connect(tgui::Signals::Button::Pressed, &ModuleDesktop::signalClickOnQuick, this);
  }

  void signalClickOnQuick(tgui::Widget::Ptr widget, const std::string &signalName) {
    ...
  }
};
```

But I get this error: 

```
undefined symbol: _ZN4tgui16SignalWidgetBase7connectIMN6packet6module13ModuleDesktopEFvSt10shared_ptrINS_6WidgetEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEJPS4_ELPv0EEEjSD_OT_DpOT0_
```

I have tgui linked and if I don't add the `signalClickOnQuick` method to the button, everything works without a problem

**Comment by texus** [comment]
Are you including TGUI as described in the tutorials or are you including Signal.hpp directly?
If you include Signal.hpp directly then you must also include SignalImpl.hpp

**Comment by colesnicov** [comment]
Thank you :blush:
