### ISSUE TITLE
Gui Builder deprecated?

### ISSUE THREAD

**Issue by colesnicov** [texus/TGUI#154]
I'll try to edit the default theme 'Black.txt', but when I try to open it with gui_builder I get this **error**:

```
~/opt/tgui/gui-builder$ ./gui-builder 
Failed to load '/home/denis/opt/tgui/themes/Black.txt', reason: No construct function exists for widget type 'CloseButton'.

```

**Comment by colesnicov** [comment]
I use branch 0.8.8

**Comment by texus** [comment]
Black.txt is a theme file (which contains information about the looks of different types of widgets) while the gui builder can only edit form files (which contains a set of widgets including their looks). Although they have a similar structure, they aren't compatible with each other.
There currently is no tool to modify theme files (you just have to use a text editor for it).

**Comment by colesnicov** [comment]
Thanks for explain.
