### ISSUE TITLE
Better documentation or more examples?

### ISSUE THREAD

**Issue by colesnicov** [texus/TGUI#155]
Hi. I'm researching the library, and so far I like it. Good job, sir.

But I can't find examples for such classes as:
`tgui :: SubwidgetContainer`
`tgui :: Panel`
`tgui :: ScrollablePanel`
`tgui :: HorizontalLayout`
`tgui :: VerticalLayout`
`tgui :: Grid`
`tgui :: SvgImage`

Of course, I can look at the documentation and gradually go through all those classes and gradually at least understandably understand it.

But without looking at the documentation, I will not know about these classes. I realize it's hard, so I'm just asking if there are any examples? Not all classes are documented or documentation is poor!

**I use branch `0.8.8`**

**Comment by texus** [comment]
I'm aware of the limited examples and tutorials, but it takes a lot of time to write them and explain them in clear way. And I already have an ever-growing todo list.

The SvgImage class is internal, it isn't intended to be used directly (it will be used when passing an svg filename to tgui::Texure). For the others you would have to do with only the documentation and maybe some info that you find when you search about them on the [forum](https://forum.tgui.eu/).

The github issues isn't the best place to ask questions btw.
You might be better off at the newly created [github discussions](https://github.com/texus/TGUI/discussions), the [tgui forum](https://forum.tgui.eu/) or on [discord](https://discord.gg/Msf4vyx). On discord you have a chance that other users might be able to answer your questions when I'm not around.

**Comment by colesnicov** [comment]
Nice.
