### ISSUE TITLE
Container get function don't search tab container panels

### ISSUE THREAD

**Issue by Groogy** [texus/TGUI#164]
If I am trying to find a widget by name that is in a panel that belongs to a tab container it will not be found. Quick look at the code is that it will be skipped by `Container::get` since it is not a container itself.

Would love if I could search the content of the panels as well instead of having to fetch the tab container first and then search each tab independently.

**Comment by texus** [comment]
I seem to have missed the notification about this, I'm only seeing this now.

This really is an edge case. The SubwidgetContainer class was meant for widgets that need a container internally but aren't containers themselves. TabContainer inherits from SubwidgetContainer but then adds multiple panels inside this internal container. Technically those panels are an implementation detail of TabContainer and aren't really part of the widget tree. But I can see why you would want the get function to return widgets inside those panels, so I'll implement it.

**Comment by Groogy** [comment]
Thank you so much!

> I seem to have missed the notification about this, I'm only seeing this now.

No worries this was still faster response than I expected :)
