### ISSUE TITLE
SS13 TGUI

### ISSUE THREAD

**Issue by lucincus** [texus/TGUI#168]
ERROR in ./packages/tgui/components/Popper.tsx 6:12-37
Module not found: Error: Can't resolve '@popperjs/core' in '/home/user/server/tgui/packages/tgui/components'
 @ ./packages/tgui/interfaces/RequestManager.js 14:14-45
 @ ./packages/tgui/interfaces/ sync ^\.\/.*$ ./RequestManager.js ./RequestManager
 @ ./packages/tgui/routes.js 19:23-54
 @ ./packages/tgui/index.js 49:17-36

ERROR in ./packages/tgui/components/Tooltip.tsx 8:12-37
Module not found: Error: Can't resolve '@popperjs/core' in '/home/user/server/tgui/packages/tgui/components'
 @ ./packages/tgui/components/index.js 134:15-35
 @ ./packages/tgui-panel/Panel.js 8:18-44
 @ ./packages/tgui-panel/index.js 60:17-35

ERROR in ./packages/tgui/interfaces/Changelog.js 18:41-62
Module not found: Error: Can't resolve 'dateformat' in '/home/user/server/tgui/packages/tgui/interfaces'
 @ ./packages/tgui/interfaces/ sync ^\.\/.*$ ./Changelog.js ./Changelog
 @ ./packages/tgui/routes.js 19:23-54
 @ ./packages/tgui/index.js 49:17-36

ERROR in ./packages/tgui/interfaces/Changelog.js 20:37-55
Module not found: Error: Can't resolve 'js-yaml' in '/home/user/server/tgui/packages/tgui/interfaces'
 @ ./packages/tgui/interfaces/ sync ^\.\/.*$ ./Changelog.js ./Changelog
 @ ./packages/tgui/routes.js 19:23-54
 @ ./packages/tgui/index.js 49:17-36

This is what I get when i compile Tgui for ss13

**Comment by lucincus** [comment]
Hopefully its due to it just being an older version but Im not fully sure

**Comment by texus** [comment]
This github repository is for a c++ library called TGUI, which is not what you seem to be using. So I can't help with this.

The project you are probably looking for is at https://github.com/tgstation/tgstation
