### ISSUE TITLE
Failed to get vendor/product ID of joystick /dev/input/js[1,0]

### ISSUE THREAD

**Issue by MykolaVaskevych** [texus/TGUI#169]
After running code from examples, I am getting these warning messages. 
```
Failed to get vendor ID of joystick /dev/input/js0
Failed to get product ID of joystick /dev/input/js0
Failed to get vendor ID of joystick /dev/input/js1
Failed to get product ID of joystick /dev/input/js1
```
How to avoid it?

**Comment by texus** [comment]
TGUI doesn't access the joystick.
This is a warning coming from SFML (from [these lines](https://github.com/SFML/SFML/blob/master/src/SFML/Window/Unix/JoystickImpl.cpp#L311-L349)).
You can disable the SFML warnings by executing `sf::err().rdbuf(nullptr);` at the beginning of your program. (You may need to include `<SFML/System/Err.hpp>`)
