### ISSUE TITLE
MessageBox doesn't resize properly

### ISSUE THREAD

**Issue by DolphyWind** [texus/TGUI#173]
Hello I want to add a message box and change its size.
My code:
'
m_youLostMsgBox = tgui::MessageBox::create("Game Over", "You Lost", { "Menu" });
m_youLostMsgBox->setSize("35%", "20%");
'
It creates a message box like this:
![image](https://user-images.githubusercontent.com/47641431/185081751-042a32f7-a26c-48ad-8818-fb65e0939e61.png)

I also tried changing its text after resizing but it acts like its never resized
My code:
'
m_youLostMsgBox = tgui::MessageBox::create();
m_youLostMsgBox->setSize("35%", "20%");
m_youLostMsgBox->setText("You Lost");
m_youLostMsgBox->setTitle("Game Over");
m_youLostMsgBox->addButton("Menu");
'
Result:
![image](https://user-images.githubusercontent.com/47641431/185082737-29795af2-d531-4e74-92b6-d5549b94da5c.png)

**Comment by texus** [comment]
Currently the size of the MessageBox is determined by its contents, not the other way around. So the setSize function can't really be used on that widget.

Maybe I could add an alternative implementation when the setSize function is called. I'm not sure what the best button sizes and locations would be if there are multiple buttons though, should they be spread out to fill the window or just keep their size based on the text and have all buttons near the center?

**Comment by DolphyWind** [comment]
I believe the best way to implement this feature is keeping their size based on the text and aligning them to left, right or center. Maybe you could add this as a function. Something like messageBox->setButtonAlignment()

**Comment by texus** [comment]
Being able to choose the alignment might also be useful when auto-sizing, e.g. when the label is longer and the OK button needs to be on the right side, so a setButtonAlignment is definitely a good idea.
Maybe a similar function can be added for the label as well, to choose whether it has to be left aligned or centered.
I might have a look at the code this weekend.
