### ISSUE TITLE
Showcase in the readme needed

### ISSUE THREAD

**Issue by Xottab-DUTY** [texus/TGUI#175]
There's no visual examples (e.g. screenshots) of how TGUI looks or what can be achieved with it.
On the website, only two examples have screenshots..

**Comment by texus** [comment]
I guess I could copy some of the screenshots that are shown on the [tgui.eu home page](https://tgui.eu/) into the readme.

Other than that I'm not sure what I could still add or where, I've never been good at showcasing my work (until half a year ago the website was still showing 7-year old screenshots).

**Comment by Xottab-DUTY** [comment]
Thanks! Awesome! :)
