### ISSUE TITLE
Arabic letters

### ISSUE THREAD

**Issue by k1epic** [texus/TGUI#179]
## The display of Arabic letters is not correct

![arabic](https://user-images.githubusercontent.com/7019625/216950559-7955bdb9-6022-491b-8e22-a91c80507509.png)

**Comment by texus** [comment]
Right-to-left writing is not supported. It would require such a big change in the way text is handled that I'm not sure if it will ever be supported.

**Comment by eXpl0it3r** [comment]
You wouldn't just need RTL, but also complex text layout, which you don't want to do manually. Luckily there are libs like HarfBuzz, maybe we'll one day add it to SFML.
