### ISSUE TITLE
High DPI Issues iOS

### ISSUE THREAD

**Issue by RGPaul** [texus/TGUI#183]
Hey,

I have some Issues when using high dpi on iOS.

1. The Tabs are drawn in different sizes (do I have to consider dpi scaling myself or will the library do it for me?)
2. If I select the text box the panel moves out of the screen (only on high dpi)

[Low DPI Video](https://1drv.ms/u/s!Aocl7ZpsRWmCjv9j4rUbZ495uG073Q?e=9doXVc)
[High DPI Video](https://1drv.ms/v/s!Aocl7ZpsRWmCjv9kkgchf5t6g581gw?e=oC2SkT)

**Comment by texus** [comment]
1) By default, TGUI doesn't handle scaling, and on a high-DPI screen everything will be smaller.
If you want to render everything with a 2x scale factor then you need to call the following functions:
```c++
gui.setRelativeView({0, 0, 0.5f, 0.5f});
tgui::getBackend()->setFontScale(2.0f);
```
The first line will scale everything, the second line is to prevent blurry text. A more detailed explanation of DPI scaling in TGUI can be found at https://tgui.eu/tutorials/1.0/dpi-scaling/

2) When touching a text field on iOS, TGUI will tell SDL where the edit box is and request the keyboard to be shown. SDL will shift the window contents upwards to keep the text field within the view and to prevent the keyboard from overlapping the text field. So my guess is that on high-DPI screens I am passing an incorrect rectangle to SDL.

Could you perhaps test whether replacing the `openVirtualKeyboard` function in `src/Backend/Window/SDL/BackendSDL.cpp` with the following code fixes the issue?
```c++
    void BackendSDL::openVirtualKeyboard(const FloatRect& rect)
    {
        Vector2i windowPointSize;
        SDL_GetWindowSize(m_guiResources.begin()->second.window, &windowPointSize.x, &windowPointSize.y);

        Vector2i windowPixelSize;
        SDL_GetWindowSizeInPixels(m_guiResources.begin()->second.window, &windowPixelSize.x, &windowPixelSize.y);

        const float dpiScaleX = static_cast<float>(windowPixelSize.x) / static_cast<float>(windowPointSize.x);
        const float dpiScaleY = static_cast<float>(windowPixelSize.y) / static_cast<float>(windowPointSize.y);

        SDL_Rect inputRect;
        inputRect.x = static_cast<int>(rect.left / dpiScaleX);
        inputRect.y = static_cast<int>(rect.top / dpiScaleY);
        inputRect.w = static_cast<int>(rect.width / dpiScaleX);
        inputRect.h = static_cast<int>(rect.height / dpiScaleY);

        SDL_SetTextInputRect(&inputRect);
        SDL_StartTextInput();
    }
```

**Comment by RGPaul** [comment]
> 1. By default, TGUI doesn't handle scaling, and on a high-DPI screen everything will be smaller.
>    If you want to render everything with a 2x scale factor then you need to call the following functions:
> 
> ```c++
> gui.setRelativeView({0, 0, 0.5f, 0.5f});
> tgui::getBackend()->setFontScale(2.0f);
> ```
> 
> The first line will scale everything, the second line is to prevent blurry text. A more detailed explanation of DPI scaling in TGUI can be found at https://tgui.eu/tutorials/1.0/dpi-scaling/

Thanks. Thats what I was looking for.

> 2. When touching a text field on iOS, TGUI will tell SDL where the edit box is and request the keyboard to be shown. SDL will shift the window contents upwards to keep the text field within the view and to prevent the keyboard from overlapping the text field. So my guess is that on high-DPI screens I am passing an incorrect rectangle to SDL.
> 
> Could you perhaps test whether replacing the `openVirtualKeyboard` function in `src/Backend/Window/SDL/BackendSDL.cpp` with the following code fixes the issue?
> 
> ```c++
>     void BackendSDL::openVirtualKeyboard(const FloatRect& rect)
>     {
>         Vector2i windowPointSize;
>         SDL_GetWindowSize(m_guiResources.begin()->second.window, &windowPointSize.x, &windowPointSize.y);
> 
>         Vector2i windowPixelSize;
>         SDL_GetWindowSizeInPixels(m_guiResources.begin()->second.window, &windowPixelSize.x, &windowPixelSize.y);
> 
>         const float dpiScaleX = static_cast<float>(windowPixelSize.x) / static_cast<float>(windowPointSize.x);
>         const float dpiScaleY = static_cast<float>(windowPixelSize.y) / static_cast<float>(windowPointSize.y);
> 
>         SDL_Rect inputRect;
>         inputRect.x = static_cast<int>(rect.left / dpiScaleX);
>         inputRect.y = static_cast<int>(rect.top / dpiScaleY);
>         inputRect.w = static_cast<int>(rect.width / dpiScaleX);
>         inputRect.h = static_cast<int>(rect.height / dpiScaleY);
> 
>         SDL_SetTextInputRect(&inputRect);
>         SDL_StartTextInput();
>     }
> ```

I tested the code and It fixes the Issue. Thanks!

**Comment by texus** [comment]
Apparently this wasn't the only scaling issue with opening the virtual keyboard. If you change the view of the gui (with e.g. the `setRelativeView` function) then the rectangle was also wrong.
I rewrote the code that calculates the rectangle (https://github.com/texus/TGUI/commit/2c5ba3492967575c6550d7fc65b6e105d962aaf5), so hopefully the latest version now works correctly in all cases.
