### ISSUE TITLE
CMake error on macOS

### ISSUE THREAD

**Issue by RGPaul** [texus/TGUI#194]
Hey texus,

I pulled some commits and since then I get the following error:

```
[cmake] CMake Error at deps/TGUI/cmake/Dependencies.cmake:253 (target_link_libraries):
[cmake]   Cannot specify link libraries for target "SDL2::SDL2main" which is not
[cmake]   built by this project.
[cmake] Call Stack (most recent call first):
[cmake]   deps/TGUI/cmake/Dependencies.cmake:263 (tgui_find_dependency_sdl)
[cmake]   deps/TGUI/src/Backend/CMakeLists.txt:158 (tgui_add_dependency_sdl)
[cmake]   deps/TGUI/src/CMakeLists.txt:287 (include)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
```

**Comment by texus** [comment]
I found one potential reason for this, but I'll need a bit more information to be certain that I fix this in the correct way.

How did you install SDL? Did it came from homebrew?

Could you try adding `message(WARNING "${TGUI_FOUND_SDL2_CONFIG} ${TGUI_FOUND_SDL2_MODULE}")` at line 156 in deps/TGUI/cmake/Dependencies.cmake to get some more information?

Are you manually specifying a value for either the SDL2_DIR or SDL2_PATH variables?

Is the error solved for you when changing `SDL2::SDL2main` to `SDL2::Main` at deps/TGUI/cmake/Dependencies.cmake line 253 where it is giving the error?

**Comment by RGPaul** [comment]
Hey, thank you for your help.

> I found one potential reason for this, but I'll need a bit more information to be certain that I fix this in the correct way.
> 
> How did you install SDL? Did it came from homebrew?

I build it from source

> 
> Could you try adding `message(WARNING "${TGUI_FOUND_SDL2_CONFIG} ${TGUI_FOUND_SDL2_MODULE}")` at line 156 in deps/TGUI/cmake/Dependencies.cmake to get some more information?
> 

Yes - it returns: TRUE FALSE

> Are you manually specifying a value for either the SDL2_DIR or SDL2_PATH variables?
> 

No - I set the CMAKE_MODULE_PATH and then use:
```
find_package(SDL2 REQUIRED)
find_package(SDL2_ttf REQUIRED)
```

> Is the error solved for you when changing `SDL2::SDL2main` to `SDL2::Main` at deps/TGUI/cmake/Dependencies.cmake line 253 where it is giving the error?

No it is not solved

Edit:
I add TGUI as subdirectory - so I can better debug
```
add_subdirectory("deps/TGUI")
```

All other libraries are added using `find_package`

Edit2:
If I remove line 251 - 257 in deps/TGUI/cmake/Dependencies.cmake, all works fine compiling and running.

**Comment by texus** [comment]
The potential reason that I had in mind would have caused the line to return "FALSE TRUE" instead of "TRUE FALSE", so this is a different issue.

I've made another wild guess at what the problem could be and committed https://github.com/texus/TGUI/commit/21567f2d44be3c0ab4ff910dce6a9a7b4b1af5eb
The change does make me wonder what would happens if you moved `find_package(SDL2)` to AFTER `add_subdirectory("deps/TGUI")`

One thing that raises questions for me is that you mention `CMAKE_MODULE_PATH`. It shouldn't be needed for recent SDL versions. Where are you setting that path to? Do you have some custom FindSDL2.cmake file?

This makes it unclear whether SDL is being found as CONFIG or MODULE. The debug print in TGUI doesn't help with this, because if the SDL target was already defined before TGUI searches for it then it simply assumes CONFIG. Could you perhaps change your find_package lines to be explicit about it, i.e. `find_package(SDL2 REQUIRED CONFIG)`?

>  If I remove line 251 - 257 in deps/TGUI/cmake/Dependencies.cmake, all works fine compiling and running.

The quick and easy solution would be to just only execute these lines when building for the MinGW compiler and not on other platforms, as this is currently the only compiler where it seems to have been required. Although I would like to better understand what is going on to fix this properly.

**Comment by RGPaul** [comment]
This commit makes it work.

> The potential reason that I had in mind would have caused the line to return "FALSE TRUE" instead of "TRUE FALSE", so this is a different issue.
> 
> I've made another wild guess at what the problem could be and committed [21567f2](https://github.com/texus/TGUI/commit/21567f2d44be3c0ab4ff910dce6a9a7b4b1af5eb) The change does make me wonder what would happens if you moved `find_package(SDL2)` to AFTER `add_subdirectory("deps/TGUI")`
> 

Still works if I moved `find_package(SDL2)` to AFTER `add_subdirectory("deps/TGUI")`

> One thing that raises questions for me is that you mention `CMAKE_MODULE_PATH`. It shouldn't be needed for recent SDL versions. Where are you setting that path to? Do you have some custom FindSDL2.cmake file?
> 

I don't use a custom FindSDL2.cmake file but I build SDL2 myself and need to tell CMake where to find that. The build creates a lib/cmake/SDL2 folder which contains files like SDL2Config.cmake that will be found then.

> This makes it unclear whether SDL is being found as CONFIG or MODULE. The debug print in TGUI doesn't help with this, because if the SDL target was already defined before TGUI searches for it then it simply assumes CONFIG. Could you perhaps change your find_package lines to be explicit about it, i.e. `find_package(SDL2 REQUIRED CONFIG)`?
> 

Works also. I just figured out that it will work even if I remove find_package(SDL2 ...) and linking to SDL2::SDL2-static.

> > If I remove line 251 - 257 in deps/TGUI/cmake/Dependencies.cmake, all works fine compiling and running.
> 
> The quick and easy solution would be to just only execute these lines when building for the MinGW compiler and not on other platforms, as this is currently the only compiler where it seems to have been required. Although I would like to better understand what is going on to fix this properly.

**Comment by texus** [comment]
> The build creates a lib/cmake/SDL2 folder which contains files like SDL2Config.cmake that will be found then.

`CMAKE_MODULE_PATH` exists to tell CMake where it can find a file called `FindSDL2.cmake` though, while SDL has `SDL2Config.cmake` in that folder (which is searched in `SDL2_DIR` if the config file isn't found automatically). The config file is the correct method to find SDL, and FindSDL2.cmake isn't an official file (so it won't exist anywhere in your SDL folder), it's just weird that you would use the module path to tell CMake where a config file is located (which is different from a module).

So I would check if it still works or not if you don't set CMAKE_MODULE_PATH, and double-check that it is finding the SDL version you built and not some other version installed system-wide.
Of course if the current method works, then I guess you can just keep doing it like this.

> I just figured out that it will work even if I remove find_package(SDL2 ...) and linking to SDL2::SDL2-static.

You should need `find_package(SDL2 ...)` somewhere. This line is called by TGUI though so maybe that is why it works if you don't call it yourself.

**Comment by RGPaul** [comment]
Yeah I think I misunderstood `CMAKE_MODULE_PATH`. It still works if I remove it.
I don't have SDL installed system wide. It will stop finding SDL if I remove the `CMAKE_PREFIX_PATH` that was set to the install path of the build dependencies.
