### ISSUE TITLE
Ability to Rename MessageBox Buttons

### ISSUE THREAD

**Issue by CasualYT31** [texus/TGUI#214]
In my current project, I have a translation system where widget texts (as well as other strings) can be reassigned throughout the GUI when a change in language is made.

Since most widgets allow you to reassign their text/s after they are created, this was relatively straightforward. However, since the `MessageBox` does not allow you to edit the captions of buttons, I've had to add a method that lets me do it. Admittedly, I'm finding it hard to come up with a scenario where I'd have to change the button captions of a `MessageBox` when it is already open, but I would at least like to have the option to, if only to match the behaviour of all the other widgets.

My current implementation of the `renameButtons()` method will accept a vector of strings, and each button is renamed from these strings. So the first button will receive the first string in the vector, the second button the second string, and so on. If there are excess strings in the vector, new buttons will be added. Then, the `MessageBox` is rearranged. The widget names of all the buttons do not change, even though they include the original caption of the widget.

I am aware that you could argue that it goes against the design of the `MessageBox` (you can't remove buttons once they are added, for example), so I wanted to hear your opinion first before I made a PR that includes my changes to allow `MessageBox` buttons to be renamed. Arguing in the opposite direction, you can set button alignments after the buttons have been added, so I don't think it's unreasonable to be able to update the text, too.

Thanks for your time! It'll be the final PR I make for a while, I promise 😅

**Comment by texus** [comment]
To keep the API simple I would just add something like a `removeButtons()` method. It would be slower to recreate the buttons like this compared to only changing the texts, but it would also provide extra flexibility as you would be able to add less buttons than you had before. Then it becomes possible to reuse a MessageBox that was created earlier.

> The widget names of all the buttons do not change, even though they include the original caption of the widget

Is this something that you want, or just a side-effect of how you implemented renameButtons? The method with `removeButtons()` would change the widget names.

> It'll be the final PR I make for a while, I promise 😅

Just now that I was getting used to someone else doing all the hard work for me :smile:

**Comment by CasualYT31** [comment]
I could add a `removeButtons(const std::vector<std::size_t>& indices = {})` method. The given vector would store the 0-based indices of the buttons to remove. If it's empty, all of them are removed. I will keep my `renameButtons()` privately though since I've already got it and it's faster and suitable for my purposes.

> Is this something that you want, or just a side-effect of how you implemented renameButtons?

It's not something I want or need in particular, just noting it in case you knew of any side effects this might have. I haven't come across any myself.

**Comment by texus** [comment]
I prefer a `removeButtons()` function without parameters.

What I would accept is a `changeButtons` function that works similar to your `renameButtons` function, but also removes buttons if the list passed to `changeButtons` contains less items than the amount of existing buttons. That way you have a single function that can be used to add, remove or rename multiple buttons at once.
