### ISSUE TITLE
iOS & Android support

### ISSUE THREAD

**Issue by zoujiaqing** [texus/TGUI#22]
SFML is suported, TGUI?

**Comment by texus** [comment]
TGUI now has experimental android support.

The tutorial can be found here: https://tgui.eu/tutorials/v06/android/

**Comment by texus** [comment]
TGUI now also has experimental iOS support.

I'm currently waiting for official sfml tutorials before I go ahead and finish my own tutorials though.

But since there is at least minimum support for android and ios now, I will be closing this issue.
