### ISSUE TITLE
How to implement a polygon window

### ISSUE THREAD

**Issue by xland** [texus/TGUI#222]
OS : Windows 10
TGUI : Latest version

To implement a polygon window on Windows the following code is required:
```c++
// WS_EX_LAYERED
hwnd = CreateWindowEx(WS_EX_LAYERED, wcx.lpszClassName, title.c_str(),
    WS_CLIPCHILDREN | WS_CLIPSIBLINGS | WS_POPUP, x, y, w, h, NULL, NULL, hinstance, static_cast<LPVOID>(this));
```

```c++
void Repaint()
{
    HDC hdc = GetDC(hwnd);
    BITMAPINFO info = { sizeof(BITMAPINFOHEADER), w, 0 - h, 1, 32, BI_RGB, pixelDataSize, 0, 0, 0, 0 };
    SetDIBits(hdc, bitmap, 0, h, pixelData, &info, DIB_RGB_COLORS); 
    BLENDFUNCTION blend = { .BlendOp{AC_SRC_OVER},.SourceConstantAlpha{255},.AlphaFormat{AC_SRC_ALPHA} };
    POINT pSrc = { 0, 0 };
    SIZE sizeWnd = { w, h };
    UpdateLayeredWindow(hwnd, hdc, NULL, &sizeWnd, compatibleDC, &pSrc, NULL, &blend, ULW_ALPHA);
    ReleaseDC(hwnd, hdc);
}
```
When window is styled by `WS_EX_LAYERED`, the window will support transparent background colors.
And mouse events will passthrough the transparent area of the window.

How to do this job when using TGUI.
Could you give me some advice?
Thanks very much.

**Comment by texus** [comment]
First of all, this has little to do with TGUI, creating and managing the window is something you do with SFML. SFML itself also won't have functionality for this, but you can get the HWND from the sf::RenderWindow with `window.getSystemHandle()` (or `window.getNativeHandle()` in SFML 3), and then you can apply your Windows-specific code to that window.

UpdateLayeredWindow is not the only way to get a polygon window, and I'm not sure how well it work together with SFML rendering (which is what TGUI will do internally). Do you need various transparency levels at different parts of your window, or is one part just fully transparent and the rest fully visible (or at least at the same alpha value)? If you just want to remove an area of the window then check out https://github.com/texus/TransparentWindows and more specifically https://github.com/texus/TransparentWindows/blob/master/Transparent.cpp#L6-L51

**Comment by xland** [comment]
Thanks very much!
