### ISSUE TITLE
Add a 2d chart or rendering 3d data for TGUI?

### ISSUE THREAD

**Issue by csunking** [texus/TGUI#224]
Does this practicable for TGUI？Or, if i want to do that, what  steps should i do?

**Comment by texus** [comment]
I think this is outside the scope of TGUI. There are so many different chart styles and complexities, you could write an entire library just for rendering charts.

You will have to render it yourself with SFML (assuming you are using SFML as backend). If the chart needs to fit in with other TGUI widgets then you can do the rendering on a canvas widget.
