### ISSUE TITLE
Chinese support?

### ISSUE THREAD

**Issue by dangyajun** [texus/TGUI#225]
I accidentally saw this great project. It would be best if it could support Chinese language. Expecting the input components to support Chinese.
build command:  cmake ../ -G "Unix Makefiles" -D TGUI_BACKEND=SFML_GRAPHICS -D TGUI_BUILD_EXAMPLES=1 -D BUILD_SHARED_LIBS=FALSE
![QQ截图20231117110857](https://github.com/texus/TGUI/assets/5320386/5f5a6d86-ba60-447e-954e-75bed1c92c76)
![QQ截图20231117110942](https://github.com/texus/TGUI/assets/5320386/8854a736-6a0f-4904-8e24-6c6040f10c9e)

**Comment by texus** [comment]
TGUI supports chinese characters, only the default font (DejaVuSans) does not.

If you change the font (by e.g. calling `tgui::Font::setGlobalFont("filename.ttf")` after the Gui is created) with a font that contains the Chinese characters then TGUI will render them.

On Windows you can use e.g. `"C:\\Windows\\Fonts\\simhei.ttf"` as filename.

**Comment by dangyajun** [comment]
Nice to receive your reply, thank you very much！
![QQ截图20231117155138](https://github.com/texus/TGUI/assets/5320386/f22e1ddd-8024-4331-b350-17c888f8a510)

**Comment by dangyajun** [comment]
On Windows the ttf file using "C:\\Windows\\Fonts\\simhei.ttf" is ok. but An error occurs when the program uses the specified ttf file.
![QQ截图20231117161206](https://github.com/texus/TGUI/assets/5320386/38030f3d-479b-4e0c-a053-c708cbe13592)
![aaaaaaaaaaaaaaaaa](https://github.com/texus/TGUI/assets/5320386/f9d3525b-e69f-4561-9bc2-726dfe96cb79)

**Comment by texus** [comment]
Are you certain that SourceCodePro contains chinese characters?
I don't see Chinese listed under "Asia" when scrolling down at https://fonts.google.com/specimen/Source+Code+Pro/glyphs, while e.g. https://fonts.google.com/noto/specimen/Noto+Sans+TC/glyphs does list Chinese explicitly.

**Comment by dangyajun** [comment]
I always thought that each ttf would include the text of all countries or ethnic groups.My knowledge has expanded again, thank you very much for your answer。
