### ISSUE TITLE
[Question] How to compile my first example of TGUI ?

### ISSUE THREAD

**Issue by mast3rz3ro** [texus/TGUI#232]
Hi there,

I have downloaded TGUI mingw64 edition which already comes with SFML backend support, and I'm trying to compile the official example provided by TGUI documentation [here](https://tgui.eu/tutorials/latest-stable/backend-sfml-graphics/)

example.c
```
#include <TGUI/TGUI.hpp>
#include <TGUI/Backend/SFML-Graphics.hpp>

int main()
{
    sf::RenderWindow window{{800, 600}, "TGUI example - SFML_GRAPHICS backend"};
    tgui::Gui gui{window};
    gui.mainLoop(); // See below for how to use your own main loop
}
```

my compile command:
```
$ gcc example -o exmaple.exe
test.c:1:10: fatal error: TGUI/TGUI.hpp: No such file or directory
    1 | #include <TGUI/TGUI.hpp>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
```

after I have include TGUI:
```
$ gcc example.c -o example -I/MingW_WinLibs/mingw64/TGUI-1.1/include
In file included from /MingW_WinLibs/mingw64/TGUI-1.1/include/TGUI/Layout.hpp:29,
                 from /MingW_WinLibs/mingw64/TGUI-1.1/include/TGUI/Animation.hpp:29,
                 from /MingW_WinLibs/mingw64/TGUI-1.1/include/TGUI/Core.hpp:30,
                 from /MingW_WinLibs/mingw64/TGUI-1.1/include/TGUI/TGUI.hpp:30,
                 from test.c:1:
/MingW_WinLibs/mingw64/TGUI-1.1/include/TGUI/Config.hpp:208:18: fatal error: iostream: No such file or directory
  208 |         #include <iostream>
      |                  ^~~~~~~~~~
compilation terminated.
```

Trying to include other missing header:
```
$ gcc example.c -o example -I/MingW_WinLibs/mingw64/TGUI-1.1/include -I/e/MingW_WinLibs/mingw64/include/c++/13.2.0
In file included from /MingW_WinLibs/mingw64/TGUI-1.1/include/TGUI/Config.hpp:141,
                 from /MingW_WinLibs/mingw64/TGUI-1.1/include/TGUI/Layout.hpp:29,
                 from /MingW_WinLibs/mingw64/TGUI-1.1/include/TGUI/Animation.hpp:29,
                 from /MingW_WinLibs/mingw64/TGUI-1.1/include/TGUI/Core.hpp:30,
                 from /MingW_WinLibs/mingw64/TGUI-1.1/include/TGUI/TGUI.hpp:30,
                 from test.c:1:
/MingW_WinLibs/mingw64/include/c++/13.2.0/version:38:10: fatal error: bits/c++config.h: No such file or directory
   38 | #include <bits/c++config.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.

```

I have tried this on [MSYS2](https://www.msys2.org/) with [winlibs](http://winlibs.com/) MINGW

P/S: I get the same error even If I have try this with MSYS2 alone.

**Comment by texus** [comment]
You are compiling your program as C instead of C++, which is why files like `<iostream>` don't exist.

Change the extension of your file from `.c` to `.cpp`. You probably also need to use `g++` instead of `gcc`.
You probably don't need to add the `include/c++` directory in the command line afterwards, only the TGUI and SFML include directories.

**Comment by mast3rz3ro** [comment]
You are right, after changing the extension into `.cpp` I'm no longer getting the `<iostream>` not found
but now I'm running into another errors:

```
$ g++ -o example example.cpp
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccMER5f8.o:example.cpp:(.text+0x34): undefined reference to `__imp__ZN2sf9VideoModeC1Ejjj'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccMER5f8.o:example.cpp:(.text+0x67): undefined reference to `__imp__ZN2sf6StringC1EPKcRKSt6locale'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccMER5f8.o:example.cpp:(.text+0xeb): undefined reference to `__imp__ZN2sf12RenderWindowC1ENS_9VideoModeERKNS_6StringEjRKNS_15ContextSettingsE'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccMER5f8.o:example.cpp:(.text+0x16b): undefined reference to `__imp__ZN4tgui14BackendGuiSFML8mainLoopENS_5ColorE'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccMER5f8.o:example.cpp:(.text+0x18a): undefined reference to `__imp__ZN2sf12RenderWindowD1Ev'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccMER5f8.o:example.cpp:(.text+0x1e9): undefined reference to `__imp__ZN2sf12RenderWindowD1Ev'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccMER5f8.o:example.cpp:(.text$_ZN4tgui13SFML_GRAPHICS3GuiC1ERN2sf12RenderWindowE[_ZN4tgui13SFML_GRAPHICS3GuiC1ERN2sf12RenderWindowE]+0x1d): undefined reference to `__imp__ZN4tgui14BackendGuiSFMLC2Ev'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccMER5f8.o:example.cpp:(.text$_ZN4tgui13SFML_GRAPHICS3GuiC1ERN2sf12RenderWindowE[_ZN4tgui13SFML_GRAPHICS3GuiC1ERN2sf12RenderWindowE]+0x26): undefined reference to `__imp__ZTVN4tgui13SFML_GRAPHICS3GuiE'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccMER5f8.o:example.cpp:(.text$_ZN4tgui13SFML_GRAPHICS3GuiC1ERN2sf12RenderWindowE[_ZN4tgui13SFML_GRAPHICS3GuiC1ERN2sf12RenderWindowE]+0x52): undefined reference to `__imp__ZN4tgui13SFML_GRAPHICS3Gui9setWindowERN2sf12RenderWindowE'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccMER5f8.o:example.cpp:(.text$_ZN4tgui13SFML_GRAPHICS3GuiC1ERN2sf12RenderWindowE[_ZN4tgui13SFML_GRAPHICS3GuiC1ERN2sf12RenderWindowE]+0x67): undefined reference to `__imp__ZN4tgui14BackendGuiSFMLD2Ev'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccMER5f8.o:example.cpp:(.text$_ZN4tgui13SFML_GRAPHICS3GuiD1Ev[_ZN4tgui13SFML_GRAPHICS3GuiD1Ev]+0xf): undefined reference to `__imp__ZTVN4tgui13SFML_GRAPHICS3GuiE'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccMER5f8.o:example.cpp:(.text$_ZN4tgui13SFML_GRAPHICS3GuiD1Ev[_ZN4tgui13SFML_GRAPHICS3GuiD1Ev]+0x28): undefined reference to `__imp__ZN4tgui14BackendGuiSFMLD2Ev'
collect2.exe: error: ld returned 1 exit status

```

**Comment by texus** [comment]
You need to link to SFML and TGUI, so you will need to add `-ltgui -lsfml-graphics -lsfml-window -lsfml-system` somewhere in that `g++ -o example example.cpp` command

If it would fail to find those libraries automatically then you may also need to add the paths to the libraries with the `-L` parameter.

**Comment by mast3rz3ro** [comment]
Hi,

Now I can compile without errors but I'm not able to run it.

My compile command:
`$ g++ -o test test.cpp -ltgui -lsfml-graphics -lsfml-window -lsfml-system`

I tried to run it from MSYS2's terminal but i didn't get any output, so then I copied all the required shared libraries into my work folder. trying to execute prints me the entry could not be located message (Please see the attached picture).
<img width="591" alt="tgui_entry_not_found" src="https://github.com/texus/TGUI/assets/151698592/812102aa-67d5-4864-afe1-868f61ee8aee">


`The procedure entry point _ZNK2sf4Font10getKerningEjjjb could not be located in the dynamic library libsfml-graphics-2.dll`

I have tried this on Windows 7 x64 with fresh MSYS2 Install + TGUI provided by MSYS2 packages.

**Comment by texus** [comment]
Procedure entry point errors like that can occur when you use a wrong dll file. Are you certain those dll files came from the MSYS2 install that you used to build the exe?

Other than that I don't know what the issue can be. I just ran the following commands in MSYS2 (on Windows 10) and the TGUI window showed up without issues.
```bash
pacman -S mingw64/mingw-w64-x86_64-tgui
g++ -o example example.cpp -ltgui -lsfml-graphics -lsfml-window -lsfml-system
./example.exe
```

Maybe you can first try getting a basic SFML example running that doesn't use TGUI (i.e. remove `-ltgui` from the command and use the following example code)?
```c++
#include <SFML/Graphics.hpp>
int main()
{
    sf::RenderWindow window(sf::VideoMode(800, 600), "SFML window");
    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();
        window.display();
    }
}
```

If that also doesn't work then the issue lies with SFML.
If that does works then the issue has to lie somewhere in the combination of using both SFML and TGUI (e.g. the SFML version being linked not being the same version as the one TGUI was compiled with).

**Comment by mast3rz3ro** [comment]
> Procedure entry point errors like that can occur when you use a wrong dll file. Are you certain those dll files came from the MSYS2 install that you used to build the exe?

Yes, I'm sure because I have already tried with a clean MSYS2 Install.

> Maybe you can first try getting a basic SFML example running that doesn't use TGUI (i.e. remove -ltgui from the command and use the following example code)?
<img width="620" alt="basic_tgui_window" src="https://github.com/texus/TGUI/assets/151698592/9a808741-9d6e-4f7f-aa06-ed267e787e7e">

> If that also doesn't work then the issue lies with SFML.
If that does works then the issue has to lie somewhere in the combination of using both SFML and TGUI (e.g. the SFML version being linked not being the same version as the one TGUI was compiled with).

I'll try again with precompiled mingw64 version and let you know.

**Comment by mast3rz3ro** [comment]
I have tried to replace the `tgui.dll` with one from precompiled mingw64 and it's asked for a different library name `sfml-graphics-2.dll` and the one I have is `libsfml-graphics-2.dll`, trying to rename this library will lead to previous error `The procedure entry point _ZNK2sf4Font10getKerningEjjjb could not be located in the dynamic library sfml-graphics-2.dll`
<img width="740" alt="2024-01-07_221220" src="https://github.com/texus/TGUI/assets/151698592/2308ec5d-5562-4dbc-ac44-51a62e6e48e8">
<img width="882" alt="2024-01-07_221119" src="https://github.com/texus/TGUI/assets/151698592/98c5c6b7-ca26-4668-af7d-63214561fac2">


I'm using `msys2-x86_64-20221028` (the last MSYS2 which supported Windows 7)
I Installed TGUI via below method:

```
$ pacman -U mingw-w64-x86_64-tgui-1.1.0-1-any.pkg.tar.zst
```

And then it's automatically started downloading other required libraries.
I have checked the SFML package name and it is `mingw-w64-x86_64-sfml-2.5.1-4-any.pkg.tar.zst`

**Comment by texus** [comment]
What is the output when you run `g++ -v`?

**Comment by mast3rz3ro** [comment]
> What is the output when you run g++ -v?

I'm using gcc version 12.2.0 here is the output:
```
$ g++ -v
Using built-in specs.
COLLECT_GCC=C:\msys64\mingw64\bin\g++.exe
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-12.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/include --libexecdir=/mingw64/lib --enable-bootstrap --enable-checking=release --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++,jit --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts --enable-libstdcxx-time --disable-libstdcxx-pch --enable-lto --enable-libgomp --disable-multilib --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev4, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --disable-libstdcxx-debug --with-boot-ldflags=-static-libstdc++ --with-stage1-ldflags=-static-libstdc++
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (Rev4, Built by MSYS2 project)

```

**Comment by texus** [comment]
The issue is that you are using SFML 2.5.1 while the TGUI package was build with SFML 2.6.1

In SFML 2.6 an additional bool parameter was added to the getKerning function. The TGUI library is looking for `_ZNK2sf4Font10getKerningEjjjb` while the SFML 2.5.1 dll only contains `_ZNK2sf4Font10getKerningEjjj` (no `b` at the end).

You will either need to install the SFML 2.6.1 package, or build TGUI yourself with CMake.

**Comment by mast3rz3ro** [comment]
Actually I had already tried before to build `TGUI` from source but it's was leading to the same mentioned errors, I think I was missing SFML library or maybe the changes I did has miss something.

Now here is the steps I follow to successfully build TGUI from source 

First I did fresh MSYS2 Install then with pacman I installed:
```
gcc
openssl
cmake
sfml

Since I'm using MINGW64 I used mingw-w64-x86_64 suffix
```

My build command:
```
$ cmake -S . -B Build -G 'Unix Makefiles' -D TGUI_BACKEND=SFML_GRAPHICS
$ make -c Build/
```

After compiling is completed I had to Install TGUI manually by coping the generated libraries ('tgui.dll' `libtgui.a`) and headers into my compiler folder because installing with make command didn't work.

Here is my output:
```
$ cd Build/
$ make install
Consolidate compiler generated dependencies of target tgui
[ 84%] Built target tgui
Consolidate compiler generated dependencies of target gui-builder
[100%] Built target gui-builder
Install the project...
-- Install configuration: "Release"
CMake Error at src/cmake_install.cmake:41 (file):
  file cannot create directory: C:/Program Files (x86)/TGUI/lib.  Maybe need
  administrative privileges.
Call Stack (most recent call first):
  cmake_install.cmake:42 (include)
make: *** [Makefile:100: install] Error 1
```
<img width="840" alt="tgui_basic_test_windows7" src="https://github.com/texus/TGUI/assets/151698592/a909602b-025f-403b-b765-1f12c88396ea">

Thank you for pointing this out for me !

**Comment by texus** [comment]
The install is failing because by default CMake tries to install to `C:/Program Files (x86)` which requires admin privileges (it would have worked if the msys terminal was opened as administrator).

The proper solution to fix the install would be to also set the `CMAKE_INSTALL_PREFIX` in the cmake command (i.e. adding something like `-D CMAKE_INSTALL_PREFIX=local_install_dir`). Even when installing, you would however still need to manually copy the dll file, and either copy the .a file or tell gcc where to find it with the `-L` flag. So there's no problem with just skipping the install step like you did.

**Comment by mast3rz3ro** [comment]
Hi,

I didn't close this because I wanted to compile the forms generated by `gui-builder`
with little search in TGUI forums I found the answer.

we can load the forums generated by `gui-build` by using `loadWidgetsFromFile` function, after playing with this function a little bit I have found the way to use it.

Here is an fully ready to compile simple:
```
#include <TGUI/TGUI.hpp>
#include <TGUI/Backend/SFML-Graphics.hpp>

int main()
{
    sf::RenderWindow window{{800, 600}, "TGUI example - SFML_GRAPHICS backend"};
    tgui::Gui gui{window};
    gui.loadWidgetsFromFile("form.txt");
    gui.mainLoop(); // See below for how to use your own main loop
}
```

Please note that the `form.txt` file is your generated form and it must be placed at the same location you are working from.

feel free to flag this issue as completed now !

Thank you again for everything !
