### ISSUE TITLE
[Bug] Tabs state after disabled tab click

### ISSUE THREAD

**Issue by lpogic** [texus/TGUI#234]
Hello, when we have one of the tabs selected and we click on the disabled one, the selected one lose its selected state.  If this is the intended effect, then fine. The bug for me is that when I click on a disabled tab, the background color of the selected one returns to its base state, but the text color remains in the selected state.

Sample code:
```
auto tabs = tgui::Tabs::create();
tabs->add("First", false);
tabs->add("Second", false);
tabs->add("Disabled", false);
tabs->setTabEnabled(2, false);
gui.add(tabs);
```

Select "First" tab, then click on "Disabled" tab. Output:
![1](https://github.com/texus/TGUI/assets/46203179/250eee43-0ae2-4bc0-b0f2-4f2765e71c5a)

**Comment by texus** [comment]
I'm not sure if deselecting the first tab is really a good idea, but this is done very intentionally in the code so I will leave the behavior for now.

The `updateTextColors()` is actually being called, but the order of the lines in the `deselect()` was wrong. I'll push a fix for this soon.

**Comment by texus** [comment]
Fixed by https://github.com/texus/TGUI/commit/e5e8975aa591611738eb4e2d9aea684896400d90
