### ISSUE TITLE
Cannot delete widgets inside of the gui-builder

### ISSUE THREAD

**Issue by PanAMD** [texus/TGUI#239]
I recently downloaded the library and I've been playing around with it for a bit, anyway I realized that deleting a widget from ther gui-builder editor is not possible, I do not know if I'm doing something wrong, but I haven't been able to do it.
![image](https://github.com/texus/TGUI/assets/27817992/3abd5d67-5350-489a-9dfb-76bdeb6a7a71)

**Comment by texus** [comment]
It looks like the entire right-click menu wasn't working, not just the Delete option.
Pressing the delete key or using the Widget>Delete option in the menu bar did work.
