### ISSUE TITLE
Font doesn't work if the child window is added in gui after adding widgets in child window

### ISSUE THREAD

**Issue by Aykelith** [texus/TGUI#33]
Font doesn't work if the child window is added in gui after adding widgets in child window. Tested on the full example. To reproduce the bug only move the line 138 after 144, in other words add firstly the widgets to the child window and after add the child window to the gui. I'm using v0.7-dev.

**Comment by texus** [comment]
It should be fixed now.

The fix itself was easy, finding out why the fix broke my chatbox widget was harder :smile:
