### ISSUE TITLE
Clipping with Panel

### ISSUE THREAD

**Issue by Dank-Y** [texus/TGUI#41]
It seems that Panel do not clip any more its children.
Adding `window.resetGLState();` or

	window.pushGLState();
	gui.draw();
	window.popGLState();
has no effect.
Here is a example code that shows the issue:

	#include <TGUI/Gui.hpp>
	#include <TGUI/Button.hpp>
	#include <TGUI/Panel.hpp>

	int main()
	{
		sf::RenderWindow window(sf::VideoMode(200, 200), "TGUI");
		tgui::Gui gui(window);
		gui.setGlobalFont("DejaVuSans.ttf");
		auto panel = tgui::Panel::create({100, 100});
		gui.add(panel);
		auto button = tgui::Button::create();
		button->setText("TGUI");
		button->setSize(200, 200);
		panel->add(button);

		while (window.isOpen())
		{
			sf::Event event;
			while (window.pollEvent(event))
			{
				if (event.type == sf::Event::Closed)
					window.close();
				gui.handleEvent(event);
			}
			window.clear();
			gui.draw();
			window.display();
		}
		return 0;
	}

**Comment by texus** [comment]
That code works fine for me. The button only gets displayed in the top left quadrant of the window. With or without storing the gl states.

**Comment by Dank-Y** [comment]
Ok, I apologize, I was compiling in release and I didn't installed the latest release libs of TGUI.
