### ISSUE TITLE
Cutting off the half of the last line in chatbox

### ISSUE THREAD

**Issue by klusekrules** [texus/TGUI#44]
Hi,
I found bug in chatbox in tgui 0.7 in code below:
```c++
 // Display the last lines when there is no scrollbar
if (!m_scroll)
{
    if (positionY > getSize().y)
    {
        float diff = positionY - getSize().y;
        for (auto it = m_panel->getWidgets().begin(); it != m_panel->getWidgets().end(); ++it)
            (*it)->setPosition({(*it)->getPosition().x, (*it)->getPosition().y - diff});
    }
}
```

When in chatbox is no scrollbar, appears an error in the calculation of positionY and it cause cutting off half of the last line.

I try change getSize().y on m_panel->getSize().y and it help. After that change it looks good.

**Comment by texus** [comment]
Thanks for reporting, your issues should be fixed now.
