### ISSUE TITLE
The problem of loading decimal numbers from saved widgets.

### ISSUE THREAD

**Issue by klusekrules** [texus/TGUI#46]
I found problem in functionality of loading/saving widgets in TGUI v0.7.
In my application I'm using polish locale. In Poland we are using ',' as separator in decimal numbers.
When I save widget in size: width = 10.5 and height = 11.5 then the output file contain:

> Size: (10,5, 11,5);

The reading function doesn't handle it.

**Comment by texus** [comment]
I didn't know it would be saved in a different way depending on the locale. I thought it would always use a dot, since this is what you have to use inside c++ anyway.

I'll look into this issue, I just hope that it doesn't also start saving larger number like "10,000.00" in some locales, because then it would get even worse to parse. But I'm actually going to see if I can always just save the one with the dot instead of depending on the locale, that would be easier.

I may ask you to test some code snippet later to tell me what it does because I may not be able to test this myself.

**Comment by klusekrules** [comment]
No problem, I will do it.

**Comment by texus** [comment]
Could you show the output of the following program?
``` c++
#include <iostream>
#include <string>
#include <sstream>

template <typename T>
std::string to_string_1(T value)
{
    std::ostringstream oss;
    oss << value;
    return oss.str();
}

template <typename T>
std::string to_string_2(T value)
{
    std::ostringstream oss;
    oss.imbue(std::locale::classic());
    oss << value;
    return oss.str();
}
    
int main()
{
    float f = 1.5f;
    std::cout << f << std::endl;
    std::cout << std::to_string(f) << std::endl;
    std::cout << to_string_1(f) << std::endl;
    std::cout << to_string_2(f) << std::endl;
    std::cout << std::stof("2.5") << std::endl;
    std::cout << std::stof("2,5") << std::endl;
}
```

**Comment by klusekrules** [comment]
I'll do it today later. Over the next two and a half hours I do not have access to the computer.

**Comment by klusekrules** [comment]
The output of the above program:
>1.5
1.500000
1.5
1.5
2.5
2

but when I added at the beginning of the main something like this:

```cpp
...
int main()
{
	std::locale pl("Polish");
	std::locale::global(pl);
	float f = 1.5f;
...
```
The output is following:
>1.5
1,500000
1,5
1.5
2
2.5

**Comment by texus** [comment]
The to_string worked like I expected but I hoped that the 5th number would stay 2.5 after changing the locale. So could you show the result of the following code as well? The 7th number should be 2.3 if all goes well.
``` c++
#include <iostream>
#include <string>
#include <sstream>

int stoi(const std::string& value)
{
    int result;
    std::istringstream iss(value);
    iss >> result;
    return result;
}

float stof(const std::string& value)
{
    float result;
    std::istringstream iss(value);
    iss >> result;
    return result;
}

int stoi_l(const std::string& value)
{
    int result;
    std::istringstream iss(value);
    iss.imbue(std::locale::classic());
    iss >> result;
    return result;
}

float stof_l(const std::string& value)
{
    float result;
    std::istringstream iss(value);
    iss.imbue(std::locale::classic());
    iss >> result;
    return result;
}
    
int main()
{
    std::locale pl("Polish");
    std::locale::global(pl);

    std::cout << stoi("2.3") << std::endl;
    std::cout << stoi("2,3") << std::endl;
    std::cout << stof("2.3") << std::endl;
    std::cout << stof("2,3") << std::endl;
    std::cout << stoi_l("2.3") << std::endl;
    std::cout << stoi_l("2,3") << std::endl;
    std::cout << stof_l("2.3") << std::endl;
    std::cout << stof_l("2,3") << std::endl;
}
```

**Comment by klusekrules** [comment]
Here is output:
>2
2
2
2.3
2
2
2.3
2

**Comment by texus** [comment]
Thanks for testing, your problem should be fixed in the latest version.
