### ISSUE TITLE
Proposition: Greater flexibility read and write functions.

### ISSUE THREAD

**Issue by klusekrules** [texus/TGUI#47]
Can you change in class WidgetLoader in function load the stringstream on istream? 
Then widgets can be loaded directly from file and the current functionality will be untouched. 

A similar change can be made in class WidgetSaver, instead of stringstream used ostream.

**Comment by texus** [comment]
You are not supposed to use WidgetLoader and WidgetSaver directly, you should call loadWidgetsFromFile or loadWidgetsFromStream on the Gui or Container class.

I should probably remove WidgetLoader and WidgetSaver from the documentation.

**Comment by klusekrules** [comment]
Oh, I did not notice these methods. Sorry.
