### ISSUE TITLE
connect/disconnect id mismatch

### ISSUE THREAD

**Issue by tatze82** [texus/TGUI#49]
There is a mismatch between the id a function receives when it is connected and the one returned from the connect function. 

Inside connect, function registered with: id
Value returned from connect: id+1. 

This leads to an exception when disconnect is called with the returned id. I have this behavior, e.g., when connecting/disconnecting a function to the clicked signal of a button.

**Comment by texus** [comment]
Thanks for reporting, it has been fixed in the latest version.

**Comment by texus** [comment]
Thanks for reporting, it has been fixed in the latest version.
