### ISSUE TITLE
Allow capture of control keys in editbox

### ISSUE THREAD

**Issue by coldeasy** [texus/TGUI#50]
It would be useful to be able to capture things like "UP" or "CTRL-K" in an EditBox. One use case I've found recently was when using the EditBox as command input and allowing a history. Being able to capture the arrow keys here would make it easier to navigate the history.

**Comment by texus** [comment]
There are probably other things that could be useful, but I can't check every key combination and send you a callback about it. So it would probably be better if you just checked these events yourself in your event loop when editBox->isFocused() is true and handle the case there.

**Comment by coldeasy** [comment]
Fair enough, just thought a general approach might be useful.
