### ISSUE TITLE
Issue in layout as a string

### ISSUE THREAD

**Issue by klusekrules** [texus/TGUI#51]
When I used layout as a string like this : 
```c++
label_->setPosition({"&.w < w ? 0 : (&.w - w) / 2"}, { "&.h < h ? 0 : (&.h - h) / 2" });
```
the condition in this expression is incorrectly calculated. Instead of 
```c++
&.w < w
&.h < h
```
is calculated:
```c++
&.w > w
&.h > h
```

**Comment by texus** [comment]
There are so many tests for the Layout class and still this issue managed to stay undetected. It's fixed now.
