### ISSUE TITLE
Question about Layout

### ISSUE THREAD

**Issue by klusekrules** [texus/TGUI#53]
String expression to counting dynamically size and position of widgets looks cool :+1:  
I wonder, how it will be behave this mechanism used in many widgets? Did you do performance tests?

Have you considered using lambda expressions? I know that could be impossibly to used it with the save/load functionality and could be probably a lot of other problems about which i don't know. What do you think about that?

**Comment by texus** [comment]
I don't think the performance is that important, the string isn't evaluated every frame, only when you actually change the size or position of a widget. Performance can always be improved in the future, initially the most important thing is that it works.

What exactly do you mean by using lambda expressions? Using them where? Could you give a small example?

**Comment by klusekrules** [comment]
Now to counting dynamically we must write something like that:  
```c++
label->setPosition({ "{&.h+(&.w-&.h-20)*0.715+5,3+(&.h-10)*0.05}" });
```

The same code with lambda expression:
```c++
label->setPosition({ [label]()->float { 
			auto w = label->getParent()->getSize().x;
			auto h = label->getParent()->getSize().y;
			return h + (w - h - 20) * 0.715 + 5;
		} },{ [label]()->float {
			auto h = label->getParent()->getSize().y;
			return 3 + (h - 10) * 0.05;
		}});
```

When we used to this lambda expression we have more possibilities. In lambda expression we can use function which we want. And there is no need to use parser.

**Comment by texus** [comment]
At first I thought this was a great idea, it wouldn't even be that hard to implement. But then I realized that it can't work: there is no way the label could know when to recalculate its position.

**Comment by klusekrules** [comment]
What a pity! I see, we would have to manually add the signals, but it cause obfuscated code and it is potential place to make a mistake.
