### ISSUE TITLE
Exception when load from file

### ISSUE THREAD

**Issue by klusekrules** [texus/TGUI#55]
When I loaded gui from file and widget have name with space then I received tgui::Exception.

**Comment by texus** [comment]
Try putting quotes around the name. Having a space or a special symbol like a dot otherwise tells the parser that the end of the name was reached.

**Comment by klusekrules** [comment]
Now I using without space (it's not problem for me), but a file was generated by gui.saveWidgetsToFile(). I don't change nothing in a file.

**Comment by texus** [comment]
It's not recommended to use spaces anyway, but that is not an excuse for saveWidgetsToFile to generate invalid files. I'll look into this later.
