### ISSUE TITLE
Proposition: The order of addition of the line in ChatBox.

### ISSUE THREAD

**Issue by klusekrules** [texus/TGUI#57]
I have proposition of new feature in ChatBox widget. Now ChatBox adds line always at the bottom of the list. I propose to add an attribute to class and/or a parameter to the add function which informs about the order of the insertion elements (new at the top or new at the bottom of the list).

**Comment by texus** [comment]
In which situation would you expect the new line to appear at the top? I can't immediately think of any use cases.

**Comment by klusekrules** [comment]
I'm using the chatbox as the log console. Perfectly suited to this, but in few place in my program it will be better to show the newest lines at the top. When I used TGUI 0.6, I created my own widget to this, but after migration to 0.7 I try in the first place use your library and only if there is no other way then create my own control, to prevent duplication of controls.

**Comment by texus** [comment]
Ok, you can add this before calling the addLine function now:
``` c++
chatbox->setNewLinesBelowOthers(false);
```

**Comment by klusekrules** [comment]
Could you add this attribute to save/load functionality ?

**Comment by texus** [comment]
Sure, I forgot to do that. New version can now save and load it and also doesn't reset the option when the chatbox is copied.

**Comment by klusekrules** [comment]
I found one small issue. When ChatBox exceed the maximum lines and m_newLinesBelowOthers = false should be remove last widget not first.

**Comment by texus** [comment]
fixed
