### ISSUE TITLE
Add a Time Widget

### ISSUE THREAD

**Issue by reworks** [texus/TGUI#66]
So I thought of adding in a Time Widget which is just a label that updates itself to the current system time.

I can open a pull request if your interested, or you can do it. I don't mind.

Thoughts?

**Comment by texus** [comment]
I think this belongs more into your own code than in a gui library.

**Comment by reworks** [comment]
I thought of it because in alot of games, especially on the menu, usually in one of the corners there is a widget that keeps track of system time.

**Comment by texus** [comment]
I think it is too specific to certain games (I actually can't think of any game where I have seen the system time being displayed). It it also not that hard to implement yourself, you just have to call lable->setText every time you need the time to update.

**Comment by reworks** [comment]
Alright, cool. Ill close this then.
