### ISSUE TITLE
Ambiguous "abs" function call

### ISSUE THREAD

**Issue by Sygmei** [texus/TGUI#70]
When I tried to compile TGUI, I got this error : 

`TGUI\src\Widgets\Knob.cpp:370:77: error: call of overloaded 'abs(float)' is ambiguous`

```cpp
allowedAngle = 360 - abs(m_endRotation - m_startRotation);
```

(There is 3 other occurrences of abs in this file)

I could fix it by using `std::abs` instead of `abs`.
I'm using mingw64 on Windows 7 g++ version 6.2.0

**Comment by texus** [comment]
Are you certain the TGUI version you have is unmodified?
According to git blame, that line has contained "std::abs" since it was written 4 years ago.

That code is also not on line 370 in any TGUI version.

**Comment by Sygmei** [comment]
Sorry, I should have checked the code on the repo instead of mine, don't know why is it modified though, thanks !
