### ISSUE TITLE
Widget.setSize segmentation fault

### ISSUE THREAD

**Issue by unlink2** [texus/TGUI#71]
It appears that setSize causes a segmentation fault when using it like this (taken from example program):

`picture->setSize(tgui::bindMax(800, windowWidth), tgui::bindMax(600, windowHeight));`

I'm using TGUI version 0.7.4 and SFML 2.2.3 on Linux 64 bit.

**Comment by texus** [comment]
Are windowWidth or windowHeight changed somewhere? There layout objects don't work like normal objects, e.g. calling their assignment operation (other than the first assignment) can cause crashes in certain cases.

Could you write some minimal code that reproduces the segfault that I can just copy-paste and run here?

**Comment by texus** [comment]
Is this still an issue?
The example code itself works fine here.
