### ISSUE TITLE
Bug: Minimize & Maximize buttons are not present in Black theme.

### ISSUE THREAD

**Issue by prybicki** [texus/TGUI#74]

**Comment by texus** [comment]
They are actually missing in all 3 theme files shipped with tgui. The person who requested these buttons didn't need the textures, so I never made an effort to update the theme files. Feel free to update the theme yourself and send a pull request for this. I don't have any matching maximize and minimize buttons.

**Comment by texus** [comment]
I decided to just create some images that match with the close button a bit (as I can't find the original source anymore). It's not perfect, but its better than not having any images.
