### ISSUE TITLE
[0.8-DEV] Change the color of text on  TextBox and CheckBox

### ISSUE THREAD

**Issue by Togtja** [texus/TGUI#80]
I can't change the text's color on TextBox nor CheckBox. Seeing as the CheckBox text matches the background color. I don't know if I am just reading the documentation wrong, or weather this isn't a function

**Comment by texus** [comment]
`textbox->getRenderer()->setTextColor(sf::Color::Red);` should work. If not, could you show the code that you are using?

**Comment by Togtja** [comment]
Thanks, that did the trick!
Does this stand anywhere in the documentation? Or am I just horribly blind

**Comment by texus** [comment]
I admit that the documentation can be pretty hard to navigate if you don't know where to search, but the functionality is documented. Links to documentation:
[TextBox::getRenderer](https://tgui.eu/documentation/0.8/classtgui_1_1TextBox.html#aa5828e4dd5560dd873ad8a776395da2c)
[TextBoxRenderer](https://tgui.eu/documentation/0.8/classtgui_1_1TextBoxRenderer.html)
[TextBoxRenderer::setTextColor](https://tgui.eu/documentation/0.8/classtgui_1_1TextBoxRenderer.html#aa04d8d02c5bcde28603b6b9864b6619d)

I suggest you read the [tutorials](https://tgui.eu/tutorials/0.8/) first to better understand the structure of the code, especially the [renderers](https://tgui.eu/tutorials/0.8/renderers/) and [themes](https://tgui.eu/tutorials/0.8/using-themes/) which talk about how the renderers work.
