### ISSUE TITLE
tgui does not honour CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by fxcoudert** [texus/TGUI#84]
After compiling with `cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/tgui/0.8.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev` and running `make install`, tgui 0.8.0 fails to install in the required directory (https://github.com/Homebrew/homebrew-core/pull/32413) with:

```
CMake Error at cmake_install.cmake:48 (file):
  file cannot create directory: /usr/local/share/tgui-0.8.  Maybe need
  administrative privileges.
```

It should not be trying to write in `/usr/local/share/tgui-0.8`, which is not inside `CMAKE_INSTALL_PREFIX`

**Comment by fxcoudert** [comment]
The issue is here: https://github.com/texus/TGUI/blob/0.8/CMakeLists.txt#L56

**Comment by texus** [comment]
Thanks for reporting this.
My cmake script is based on that of SFML and I'm not certain why they implemented it like that: https://github.com/SFML/SFML/blob/master/CMakeLists.txt#L146
So I'll have to do some testing on macOS before I can fix this as I assume the SFML developers had a reason to not use the same code on macOS as they use for linux and bsd.
