### ISSUE TITLE
A Partial TreeView Implementation

### ISSUE THREAD

**Issue by xandayn** [texus/TGUI#85]
I've made a TreeView class for my own use using TGUI, I don't plan to release the whole code of the project at this time and don't have to time to fork and implement it properly into TGUI myself, but here is my partial implementation of a TreeView class (in gist form) if someone wants to do a proper pull request.

Currently supports most expected functionality of a TGUI widget, to list a few:
- Theme Support
- Automatic Resizing
- Automatic Scrollbars (both vertical and horizontal)
- Theme Dependent Icons
- Theme Dependent Hover/Select Colors
- Etc.

Also supports collapsing/expanding nodes by double-clicking or by clicking on the icon.

Now not everything is fully implemented.
Here are some missing features that would have to be implemented:
- Setting the selected item
- Deselecting the selected item
- Removing items
- Getting the selected item
- Changing items
- Probably more but that's all I can think of off the top of my head

Also some obvious changes that would be needed from the gists are:
- Change the namespace to the tgui namespace
- Change includes to tgui includes

Here's an example of how you can create a TreeView:
```C++
auto tView = tgui::TreeView::create();
tView->setSize("&.size");
tView->addItem({"This", "Is", "Similar", "To", "MenuBars"});
tView->addItem({"Optional", "Parameter", "createParents"}, true);

tGui->add(tView);
```

And here are some previews:
![capture](https://user-images.githubusercontent.com/5209724/47948210-a0200780-dee9-11e8-8f8c-0de59a25aff7.PNG)
![capture 2](https://user-images.githubusercontent.com/5209724/47948211-a31af800-dee9-11e8-950d-d7af712b880e.PNG)
![capture 3](https://user-images.githubusercontent.com/5209724/47948212-a4e4bb80-dee9-11e8-967c-f51334f7e847.PNG)

Code Gists:
[TreeView.hpp](https://gist.github.com/xandayn/d85e3f9a21c95515a2fd09ce5657ea40)
[TreeView.cpp](https://gist.github.com/xandayn/83b53ff16dfea727c11d3c6970498177)
[TreeViewRenderer.hpp](https://gist.github.com/xandayn/ee7dd8dda0e6d63fe3c29955a3949900)
[TreeViewRenderer.cpp](https://gist.github.com/xandayn/f413557af4b3c8bd1ea099e86b3b4bce)

**Comment by texus** [comment]
Thank you for sharing this code. I'll try to finish it during the next few weeks and release it in TGUI 0.8.2.

**Comment by texus** [comment]
The TreeView widget has been added (9187229aaabe421abafd960a659f1ab5ae47bc78).

I rewrote some parts and not all functionality may have been kept (most notably the NodeIndentation property was removed). If you end up using my version of the TreeView and believe some things should be changed then just let me know, even after this gets released the API and behavior of the class won't be set in stone.
