### ISSUE TITLE
Future: Please add edit box functionability

### ISSUE THREAD

**Issue by 1aam2am1** [texus/TGUI#91]
Please add to edit box functions that cold set prefix (fox e.g unit of messure)
The prefix would be aligned right in edit box. And normal text will be normal text.

**Comment by texus** [comment]
I'll add it to the todo list.
(It's called a postfix or suffix by the way, a prefix would be on the left side of the edit box)

**Comment by 1aam2am1** [comment]
I'm not English native. But thanks to adding it to todo list.

**Comment by 1aam2am1** [comment]
I don't find form functionality in this part of code. And I can't change it in gui-builder.

**Comment by texus** [comment]
I forgot to add the loading and saving code, it has been added now.

New gui builder executable: https://www.dropbox.com/s/vxyujdt6uajti8m/gui-builder-2019-01-24.zip?dl=1
